version: '2'

services:
  example2src:
    build: 
      context: .
    ports:
      - "5000:80"
    volumes:
      - ./code/src:/app
    depends_on:
      - example2dest
    cap_add:
        - SYS_PTRACE
    links:
      - example2dest
    container_name: example2_src

  example2dest:
    build: 
      context: .
    ports:
      - "5001:80"
    volumes:
      - ./code/dest:/app
    cap_add:
        - SYS_PTRACE
    container_name: example2_dest
